### ISSUE TITLE
Problems with searching a players or chemistry - Asia\Europe

### ISSUE THREAD

**Issue by mansurjon123** [galodoido794/AUTOBOT_FIFAX#1]
Hi admin. Thank you for app.
I have problem with searching. I logged in app, i see my pofile and market.
Error: Are you logged into Fifa? Check...
Screenshots 
https://prnt.sc/lew1xe
https://prnt.sc/lew1mv 
win 7, framework and vc_redist installed.

**Comment by luibrain** [comment]
The same

**Comment by galodoido794** [comment]
This occurs when the application (Bot) can not fetch the cookie from the session logged in to FIFA.

Are you also with Chrome active in another account and using the Bot?

An important detail is that I did test only in Windows 10. 
It may be that there is some difference in Windows 7  =(

**Comment by luibrain** [comment]
I have Win 10. webapp is offline in chrome, when bot is active

**Comment by galodoido794** [comment]
Can you navigate the Ultimate Team through BOT?

**Comment by mansurjon123** [comment]
> Are you also with Chrome active in another account and using the Bot?
No, i use only bot.

> An important detail is that I did test only in Windows 10. It may be that there is some difference in Windows 7 =(
ok, i will test in win 10

**Comment by mansurjon123** [comment]
> Can you navigate the Ultimate Team through BOT?

yes, of course

**Comment by galodoido794** [comment]
I closed unintentionally

**Comment by galodoido794** [comment]
Maybe it's the area. Are you in North America, South America, Europe ....?

**Comment by luibrain** [comment]
Europe

**Comment by mansurjon123** [comment]
Cenral asia, Uzbekistan

**Comment by galodoido794** [comment]
I released version 1.1 with AutoBot_LOG.exe
Run it and then save the LOG (file .txt) here in the chat.

**Comment by luibrain** [comment]
`Error: Are you logged in to FIFA? Check ...
RESPONSE FALSE: Unauthorized
Headers: X-UT-SID | cf5daeea-2b9c-4aa5-8bbc-887687fb01e1
Headers: X-Requested-With | XMLHttpRequest
Headers: X-UT-PHISHING-TOKEN | 9093276532747233357
Headers: Easw-Session-Data-Nucleus-Id | 1006873547712
Headers: AuthToken | QVQwOjEuMDozLjA6NjA6b01wWWI1THBSSkp2THdZdGRGN29xcTg0cHpQb1llSzF3ZkQ6NDc3MTI6b2cyNm4
Headers: Authorization | Bearer QVQwOjEuMDozLjA6NjA6ZVFhemloQVJQRHo4ZTNvdDJvRVlmR1Q2Mk0zVnpCT3kxQUU6NDc3MTI6b2cyNm0
Headers: x-ea-taxv | 1.1
Headers: x-ea-game-id-type | easku
Headers: x-ea-game-id | FUT19WEB
Headers: Access-Control-Request-Method | GET
Headers: Access-Control-Request-Headers | content-type,x-ut-sid
Headers: Cache-Control | no-cache
Headers: Content-Type | application/json
Headers: Origin | https://www.easports.com
Headers: User-Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36 Firefox/42870
Headers: Upgrade-Insecure-Requests | 1
Headers: Accept-Language | ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7
Headers: Accept | */*
Cookie: ak_bmsc:3DE72CF080189386F48E8F6A62A7F18DD9D4E0AFEA0500001812E25B20CA9834~plgsP0a5OdKwbFp2ZW8Rz5dTInK30+umvR3pJyTpSY+Mzrifbex78IuyKFxW10RuxI+GkYckyn1vH6W4EEp8ZqKwt5FbN9YnkrffiNpg87yhOG6jr0z4zViBPzd+lSACLecqGZtlsMIleCjTzjTt9FfbF1c4ngcBZnx7Kam9dxQiAB8d/nq0udTgnwiM7CMrWxc0Cn58CgD1A1C796EdOz4aQyZl+o3WAc/GLhq2XQHqKoSSiRRr1e7EB35m4vWIz09qgnSkw7nfD/FWHdEFN6cEp3Dg7uSl3DoGs2scfwEqn8+ZEuE4Y0T3BAC/WvA55JzlzdgQ+ILLP3LR4l5zD1+9Djb++eo93WbMsCEB1EATzI+lw6S+LLw9n1oS1DMEye/Le3Ec3lGQ4vhXunf+B80b4IXegbZ+hVq48fQN+uBCEQDdC6TZEjxc1O+N5xXKPm3pSH+lW0RH86dLpp4UzyhjVvcszawI+Rr9iNFGafv2axORmWnnm8pB2FJ8si4RUB72qTdzA8/0rXqUr95qw8OJyaimY0NSvljjuDWYx4bDXogVE1QQx+peGMaM5i2nlxpLAuYc9QsDtFSDfWMxT3z9UshzLbupcLqDC9R9rlJFKXtcdhTZn8V+jjO0wbGUcU2aaHHvYo7czhUrpM83JmbDdfASNC4uW5pPGjHgLGyf6dp2C6nZS79G7H22R7HWKOs10QV491vYR+x/0oufiCviQHAqv/O+4ZZdNrmtrvSWBSc08lPEx220AApjgE4uiuDJS1nc0s88sjDTGb7rpIenvC4lGVxgJZeK4pQlJaivm3ZfYR3qh77l+lDPZLaE05ARzcwIaFzA5S4nKljxYenSHr6dHJdS8GqMs3UvR5LZXAebghfuK/z3lJ/hNUCFeSE9W7fUe7XxRyci/doUMgOaZdRnm7MUJaHmNf1PjkD8FbVYMi+NmzSHoPDJRIaWW90XMrPqd0bEDPmyNRWVZGuQ== | D:.easports.com | P: /
Cookie: _nx_mpcid:21a81f37-7be0-46bb-8770-6418339ac430 | D:.ea.com | P: /
Cookie: __utmb:82955028.3.10.1541542442 | D:.signin.ea.com | P: /
Cookie: utag_main:v_id:0166eb16f5320014f8f10e09f2680107201b406a00bd0$_sn:1$_ss:0$_pn:3%3Bexp-session$_st:1541544252402$ses_id:1541542442290%3Bexp-session | D:.ea.com | P: /
Cookie: isPhone:false | D:signin.ea.com | P: /
Cookie: isPogo:false | D:signin.ea.com | P: /
Cookie: webun:"luibrain05@gmail.com" | D:signin.ea.com | P: /
Cookie: __utmt:1 | D:.signin.ea.com | P: /
Cookie: __utmz:82955028.1541542442.1.1.utmcsr=easports.com|utmccn=(referral)|utmcmd=referral|utmcct=/br/fifa/ultimate-team/web-app/ | D:.signin.ea.com | P: /
Cookie: __utma:82955028.135306538.1541542442.1541542442.1541542442.1 | D:.signin.ea.com | P: /
Cookie: _gid:GA1.2.531143730.1541542442 | D:.ea.com | P: /
Cookie: _ga:GA1.2.135306538.1541542442 | D:.ea.com | P: /
Cookie: _gat:1 | D:.easports.com | P: /
Cookie: _ga:GA1.2.501600227.1541542425 | D:.easports.com | P: /
Cookie: sid:U0Z3Q0R6b0E4anJZTFpTWm5aZDFvek5kZFFmNjlYQUdia2M5MjBwSlZxTFNtZHU3N0ozTUhyWXVPNFdjUg.GF9NZ6sGqO8zJfzGntpZysPtu3K0r6gWUsNRYacNUaU | D:accounts.ea.com | P: /connect
Cookie: remid:TUU6R1gwMk02VDlGeldhdVdZblB4d0I2aE9Ya3Nic1VqQk5yM3RTeUM5TzoxMTA2NDc3MTI.m5xFpc92U6GhLCwnqzGuBAfKkJf6XPbkgU6493sp | D:accounts.ea.com | P: /connect
Search .......
`

**Comment by luibrain** [comment]
[_LOG_FIFA.txt](https://github.com/galodoido794/AUTOBOT_FIFAX/files/2555218/_LOG_FIFA.txt)

**Comment by galodoido794** [comment]
Interesting: RESPONSE FALSE: Unauthorized
I'll try to simulate here

PS: I deleted your LOG (from Github) because I had your email

**Comment by galodoido794** [comment]
I believe that in 10 minutes I make available a version to try to solve this problem.

**Comment by galodoido794** [comment]
Follow the version for you to test

https://github.com/galodoido794/AUTOBOT_FIFAX/releases/download/1.2/AUTOBOT_FIFAX_1_2_beta.zip

Let me know if it worked or not. If you did not use AUTOBOT_LOG again

**Comment by luibrain** [comment]
the same error

**Comment by galodoido794** [comment]
Attaches the LOG of version 1.2

**Comment by luibrain** [comment]
[_LOG_FIFA.txt](https://github.com/galodoido794/AUTOBOT_FIFAX/files/2555386/_LOG_FIFA.txt)

**Comment by galodoido794** [comment]
While I investigate try to clean the Cookie from Chrome (https://tinyurl.com/y78vpqn3), restart the computer and try again in version 1.2

**Comment by luibrain** [comment]
didn't help

**Comment by galodoido794** [comment]
Do this process again, but open AUTOBOT_LOG and add it here on the site

**Comment by galodoido794** [comment]
I filter some parameters to pass to EA. Maybe I'm filtering out some parameter that is mandatory for you.

**Comment by galodoido794** [comment]
Can we do remote access with TeamViewer? I'll send you an email if I still have

**Comment by luibrain** [comment]
I can do this later, need some sleep

**Comment by galodoido794** [comment]
5 minutos for tests :)

**Comment by galodoido794** [comment]
5 minutes for tests

**Comment by luibrain** [comment]
contact?

**Comment by galodoido794** [comment]
Check your personal email

**Comment by galodoido794** [comment]
https://github.com/galodoido794/AUTOBOT_FIFAX/releases/download/1.2/AUTOBOT_FIFAX_v_1_2.zip

**Comment by luibrain** [comment]
[_LOG_FIFA.txt](https://github.com/galodoido794/AUTOBOT_FIFAX/files/2555517/_LOG_FIFA.txt)
still br there

**Comment by galodoido794** [comment]
https://github.com/galodoido794/AUTOBOT_FIFAX/releases/download/1.2/AUTOBOT_FIFAX_v_1_22.zip

**Comment by galodoido794** [comment]
Check your e-mail

**Comment by galodoido794** [comment]
New Version: https://github.com/galodoido794/AUTOBOT_FIFAX/releases/download/1.3/AUTOBOT_FIFAX_v1_3.zip

**Comment by mansurjon123** [comment]
Version 1.3 it's work. Thank you bro.

**Comment by galodoido794** [comment]
@luibrain @mansurjon123 Give your like on youtube =D

**Comment by RoyFIFAxD** [comment]
Can i get banned for this?

**Comment by sander221** [comment]
hallo admin
i have problem with searching. I logged in app, i see my pofile and market.
Error: Are you logged into Fifa? Check...
