### ISSUE TITLE
error are you loggin to fifa ?

### ISSUE THREAD

**Issue by sander2211** [galodoido794/AUTOBOT_FIFAX#11]
can you help me i keep geting the same massage Error are you login to fifa ? ...

**Comment by sander2211** [comment]
[_LOG_FIFA.txt](https://github.com/galodoido794/AUTOBOT_FIFAX/files/2683116/_LOG_FIFA.txt)

**Comment by galodoido794** [comment]
From Log I saw no apparent problem. What is your problem?

Here are some steps that help with some issues:

Is your date and time correct? If you are trying the following
clear the Chrome Cache
then click on the button on the right side "Problem with Login Fifa? Try this"
delete the (AUTOBOT) folder
Restart PC
puts the BOT in another folder and tries again.
