### ISSUE TITLE
Not issue. but wanted to ask

### ISSUE THREAD

**Issue by Nikeliss** [galodoido794/AUTOBOT_FIFAX#13]
If i select to snipe baby icon. will it still pick the other version if it pops up? for example if i try matthaus 88 for 700k and 91 one pops out, will he buy it ?

**Comment by galodoido794** [comment]
[En-Us]
As no one contributed anything (on the Patreon site) I am not giving support and will not have new features. While I'm working on other BOTs

[Pt-br]
Como ninguém contribuiu com nada (no site Patreon) não estou dando suporte e não vai vai ter novos recursos. Enquanto nisso estou trabalhando em outros BOTs

https://www.patreon.com/galodoido
