### ISSUE TITLE
Help ME

### ISSUE THREAD

**Issue by erickmsms** [galodoido794/AUTOBOT_FIFAX#14]
I can not connect to my EA account, it says it can not find the file CefSharpCore

**Comment by erickmsms** [comment]
![captura de tela 141](https://user-images.githubusercontent.com/46693816/51146866-3bfdb600-183f-11e9-93e1-a8f8f146df78.png)
![captura de tela 142](https://user-images.githubusercontent.com/46693816/51146867-3bfdb600-183f-11e9-8432-b7cd4b8b643d.png)

**Comment by galodoido794** [comment]
[En-Us]
As no one contributed anything (on the Patreon site) I am not giving support and will not have new features. While I'm working on other BOTs

[Pt-br]
Como ninguém contribuiu com nada (no site Patreon) não estou dando suporte e não vai vai ter novos recursos. Enquanto nisso estou trabalhando em outros BOTs

https://www.patreon.com/galodoido
