### ISSUE TITLE
Im getting the error are you logged into fifa?

### ISSUE THREAD

**Issue by andikuci123** [galodoido794/AUTOBOT_FIFAX#15]
can you please help

**Comment by andikuci123** [comment]
[_LOG_FIFA.txt](https://github.com/galodoido794/AUTOBOT_FIFAX/files/2770832/_LOG_FIFA.txt)

**Comment by galodoido794** [comment]
[En-Us]
As no one contributed anything (on the Patreon site) I am not giving support and will not have new features. While I'm working on other BOTs

[Pt-br]
Como ninguém contribuiu com nada (no site Patreon) não estou dando suporte e não vai vai ter novos recursos. Enquanto nisso estou trabalhando em outros BOTs

https://www.patreon.com/galodoido

**Comment by andikuci123** [comment]
Oh ok thats ok

Sent from my iPhone

On 18 Jan 2019, at 21:08, Galo <notifications@github.com<mailto:notifications@github.com>> wrote:


[En-Us]
As no one contributed anything (on the Patreon site) I am not giving support and will not have new features. While I'm working on other BOTs

[Pt-br]
Como ninguém contribuiu com nada (no site Patreon) não estou dando suporte e não vai vai ter novos recursos. Enquanto nisso estou trabalhando em outros BOTs

https://www.patreon.com/galodoido

**Comment by galodoido794** [comment]
New Version: https://github.com/galodoido794/AUTOBOT_FIFAX/releases/download/1.10/AUTOBOT_FIFAXv_1_10.7z

For you go in the Problem tab and it changes server and tests. He did not change the server and test again. It should work.

**Comment by andikuci123** [comment]
yes now it is working thank you very much! you are very talented at what you do keep it up and I believe you'll get somewhere bro

**Comment by galodoido794** [comment]
could contribute: [Patreon](https://www.patreon.com/galodoido)
