### ISSUE TITLE
Sorry, an error has occured 

### ISSUE THREAD

**Issue by KilosPL** [galodoido794/AUTOBOT_FIFAX#16]
Hi guys, when i try to search player error "Are you logged in fifa? check" shows. When i try to search player on web app another error shows. Yesterday everything worked. Can you help?

![ero2](https://user-images.githubusercontent.com/46895536/51478934-24698480-1d8d-11e9-80ff-161bdbdb7770.PNG)
![error](https://user-images.githubusercontent.com/46895536/51478935-25021b00-1d8d-11e9-9ecd-aea8463a0783.PNG)
![ero](https://user-images.githubusercontent.com/46895536/51478936-25021b00-1d8d-11e9-983b-9166e561b9ac.PNG)

**Comment by galodoido794** [comment]
Use version 1.10.

Can you access the market from the Bot normally?
If so, try the following: go in the **Problem tab** and it **changes server and tests**.
He did not change the server and test again. It should work.

**Comment by VatsaPatel** [comment]
Hello @galodoido794 ,

Sorry, I can't support on patreon but am a developer & can help in adding features.

**Comment by KilosPL** [comment]
Thanks, it works
