### ISSUE TITLE
Probleme avec le logiciel

### ISSUE THREAD

**Issue by bd31600** [galodoido794/AUTOBOT_FIFAX#18]
Bonjour , en téléchargement le fichier il m est écrit que il y a un virus dans fifax
Exe

**Comment by galodoido794** [comment]
Why did not you test the url via website?

I did parsing and nothing was detected: [Site](https://www.virustotal.com/#/url/9f592282f6defcf0042359bb358822c2fafacae2d48ac50de7afdacebf460500/detection)

[pt-br]
Você pode testar a URL em algum site que detecta virus.
Segue o resultado (sem vírus) =  [Site](https://www.virustotal.com/#/url/9f592282f6defcf0042359bb358822c2fafacae2d48ac50de7afdacebf460500/detection)

**Comment by bd31600** [comment]
Merci le virus n est plus présent

**Comment by bd31600** [comment]
Merci ça remarche
