### ISSUE TITLE
issue with searching for players, etc (v1.5) - Australia

### ISSUE THREAD

**Issue by koolkid69er** [galodoido794/AUTOBOT_FIFAX#2]
doesn't work... I continually get the same message when trying to buy players -
"Error: Are you logged into Fifa? Check..."
I am logged out of fifa. Using windows 10 and I live in Australia.
I have uninstalled and reinstalled on multiple occasions. Reset my cookies/browsing data and Restarted my computer.
I have followed everything from the other issue but still cannot seem to get things to work.
Please respond I'm not sure what to do.

**Comment by galodoido794** [comment]
Run AutoBot_LOG.exe and then save the LOG (file .txt) here in the chat.

**Comment by koolkid69er** [comment]
...
Cookie: sid:U0RsZ1BUNlZ4RUVqQVhnZ2J3T1lERnl3dlUwRTZ6MzgxaHoyS0ZBaVo1aVNBUkVDV3Znd3RVVURxaUl3Rw._BCphBuxzu4N1AEP50CipKh7_zfytbEoPQc3tf2qXAQ | D:accounts.ea.com | P: /connect
Cookie: remid:TUU6UmcycG1NVUlwRVNYVVZFVEFRMHpLdzAzdFdtWVh1Wm5mMU02cTBldjoxMTEwMTYxOTQ.V1anTGJW2130zm0Bh284xSAs9HF2Dirn51dUQTQJ | D:accounts.ea.com | P: /connect
Cookie: IgniteCookieSync:true |  | P: /adserver
Cookie: audit:"ldHYj4JxXseFZyxAe5KJ2/2CL4CXknS/U44XEtpQ0xHdXCmmHvJ5s5jcHzz+8UJcCDo1Ik3FEOY6wHOIhIr/cCW540f5HQJCznOY+T/DJZwwBu2uLc0MTQ==" | | P: /exchange
Version: 1.5
Search .......

**Comment by galodoido794** [comment]
I'm analyzing

**Comment by galodoido794** [comment]
Test this new version and answer it worked

https://github.com/galodoido794/AUTOBOT_FIFAX/releases/download/1.6/AUTOBOT_FIFAX_v1_6.zip

**Comment by koolkid69er** [comment]
still doesn't appear to work. I do not have access to the transfers on the web app, maybe that is something that is causing the problem.

**Comment by koolkid69er** [comment]
here is the log for the v1.6
---------------------------------


Error: Are you logged in to FIFA? Check ...
Headers: X-UT-SID | fa876245-7792-4260-8395-d8f9357d46ce
Headers: X-Requested-With | XMLHttpRequest
Headers: Easw-Session-Data-Nucleus-Id | 1005633616194
Headers: AuthToken | QVQxOjEuMDozLjA6NjA6aWt2MzJZQzJrZXcyM1JuVTZ1Uk4wc2l6amE5SnJ1dzNPbHI6MTYxOTQ6b2c3cGk
Headers: Authorization | Bearer QVQxOjEuMDozLjA6NjA6WHZZazFzclBadDJPNzlsYUNscTk1ZExsQ2NUakFQWW9CQlM6MTYxOTQ6b2c3cGk
Headers: x-ea-taxv | 1.1
Headers: x-ea-game-id-type | easku
Headers: x-ea-game-id | FUT19WEB
Headers: Cache-Control | no-cache
Headers: Origin | https://www.easports.com
Headers: User-Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36 Firefox/92644
Headers: Upgrade-Insecure-Requests | 1
ERROR: Response false -> : 
Cookie: ak_bmsc:E31F4EE645DE02AE13C1DB78E8AAF5136866F425BA3000007A4FE75B875D611D~pl1uho9P0QNT6+O1IaDsofqyMeRtmL6mBgApa2gulKRvVBiNKHRom46cwnX/Fx1KHRcZp/4/FUuOibuiKhlSFyZgaXowQbK77+7mxLxKWim5VpwypmCdrvOmhtJkTYZFAZ0B/tcUDcAZOZ2bs8+aif/HNm5niyO39cwT7eaX0mnIkVbL5Bwn8ib4fn/zg9jCy8kdI2XEcmYSWfKAXsYGHuaq01TKWoqZt7rw4C9c/WvxIggU8CJ+/cFnrhq2w/H4ytu0uHZleMMpP+qwOiQkQYXObxryX5jyYXUVXS/MCNb6D7sHDJO2nPaxT4oJ2/aqIuj53Cwhek3sKc4sbh9C7f51eSlImhka4Vvcqdrh7FUt1SabvFEHZcge67gZEyg9o/52klG9E0yFQB194VADvrx4bc87fOeCPolBaikCjqXdKTckPfwrP9ekGFQNFmkxMa85vjWquFqOxqCse7GxTsR1H5g0SQQHytT+sXKmWiEMV9GXRZpTDUj5vBs+stLLlkFRKVK6TJ8XpaqCAbv9fKyUnfaRWErBPIhUZaHWIi28QDW9m+RSBxLKZDZUm9LXbNXEwJQyYGDNzY2leajjOUnbgeXBv7blJzwVrpLYSvHLPM9bD5NHz3s1EvPi/7xPin9uqGEoWqU7NXPuv8EgCarQ== | D:.easports.com | P: /
Cookie: _nx_mpcid:0145f977-078a-4a69-82b1-57f8fbb5c320 | D:.ea.com | P: /
Cookie: __utmb:82955028.3.10.1541885832 | D:.signin.ea.com | P: /
Cookie: utag_main:v_id:0166ff8ea9e20017682fd993dfe50007201ae06a00bd0$_sn:1$_ss:0$_pn:3%3Bexp-session$_st:1541887651667$ses_id:1541885831650%3Bexp-session | D:.ea.com | P: /
Cookie: isPhone:false | D:signin.ea.com | P: /
Cookie: isPogo:false | D:signin.ea.com | P: /
Cookie: webun:"kelciouskm@gmail.com" | D:signin.ea.com | P: /
Cookie: __utmt:1 | D:.signin.ea.com | P: /
Cookie: __utmz:82955028.1541885832.1.1.utmcsr=easports.com|utmccn=(referral)|utmcmd=referral|utmcct=/fifa/ultimate-team/web-app/ | D:.signin.ea.com | P: /
Cookie: __utmc:82955028 | D:.signin.ea.com | P: /
Cookie: __utma:82955028.925854092.1541885832.1541885832.1541885832.1 | D:.signin.ea.com | P: /
Cookie: _gid:GA1.2.1507328639.1541885832 | D:.ea.com | P: /
Cookie: _ga:GA1.2.925854092.1541885832 | D:.ea.com | P: /
Cookie: _gat:1 | D:.easports.com | P: /
Cookie: _ga:GA1.2.1342343516.1541885820 | D:.easports.com | P: /
Cookie: JSESSIONID:EF778965535E869647A08A4C8968CF6A.prdaccountc-32 | D:signin.ea.com | P: /p
Cookie: remid:TUU6S1Zld2ZKV0tMd1dLT2NGSGdxenZMSHFSajhWSXdQb1NmSE8wanFGOToxMTEwMTYxOTQ.LA7jxyC3qSNtQQ4M0TgTX27QuzYHDS3Mi1egtB1s | D:accounts.ea.com | P: /connect
Cookie: sid:U2t6U1VZN1o1blA5WktwakJDZDZlRWszSmR2S3hLdDVNVjVNVGtZRFM5aXFvQjNPOWhuMHE4R2JiNTdIaQ.Dmna08bQUSWTe4Tw2TNXEHrXMVs3h-OsdXIQZzWH5z4 | D:accounts.ea.com | P: /connect
Headers: X-UT-SID | fa876245-7792-4260-8395-d8f9357d46ce
Headers: X-Requested-With | XMLHttpRequest
Headers: Easw-Session-Data-Nucleus-Id | 1005633616194
Headers: AuthToken | QVQxOjEuMDozLjA6NjA6aWt2MzJZQzJrZXcyM1JuVTZ1Uk4wc2l6amE5SnJ1dzNPbHI6MTYxOTQ6b2c3cGk
Headers: Authorization | Bearer QVQxOjEuMDozLjA6NjA6WHZZazFzclBadDJPNzlsYUNscTk1ZExsQ2NUakFQWW9CQlM6MTYxOTQ6b2c3cGk
Headers: x-ea-taxv | 1.1
Headers: x-ea-game-id-type | easku
Headers: x-ea-game-id | FUT19WEB
Headers: Cache-Control | no-cache
Headers: Origin | https://www.easports.com
Headers: User-Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36 Firefox/92644
Headers: Upgrade-Insecure-Requests | 1
Cookie: ak_bmsc:E31F4EE645DE02AE13C1DB78E8AAF5136866F425BA3000007A4FE75B875D611D~pl1uho9P0QNT6+O1IaDsofqyMeRtmL6mBgApa2gulKRvVBiNKHRom46cwnX/Fx1KHRcZp/4/FUuOibuiKhlSFyZgaXowQbK77+7mxLxKWim5VpwypmCdrvOmhtJkTYZFAZ0B/tcUDcAZOZ2bs8+aif/HNm5niyO39cwT7eaX0mnIkVbL5Bwn8ib4fn/zg9jCy8kdI2XEcmYSWfKAXsYGHuaq01TKWoqZt7rw4C9c/WvxIggU8CJ+/cFnrhq2w/H4ytu0uHZleMMpP+qwOiQkQYXObxryX5jyYXUVXS/MCNb6D7sHDJO2nPaxT4oJ2/aqIuj53Cwhek3sKc4sbh9C7f51eSlImhka4Vvcqdrh7FUt1SabvFEHZcge67gZEyg9o/52klG9E0yFQB194VADvrx4bc87fOeCPolBaikCjqXdKTckPfwrP9ekGFQNFmkxMa85vjWquFqOxqCse7GxTsR1H5g0SQQHytT+sXKmWiEMV9GXRZpTDUj5vBs+stLLlkFRKVK6TJ8XpaqCAbv9fKyUnfaRWErBPIhUZaHWIi28QDW9m+RSBxLKZDZUm9LXbNXEwJQyYGDNzY2leajjOUnbgeXBv7blJzwVrpLYSvHLPM9bD5NHz3s1EvPi/7xPin9uqGEoWqU7NXPuv8EgCarQ== | D:.easports.com | P: /
Cookie: _nx_mpcid:0145f977-078a-4a69-82b1-57f8fbb5c320 | D:.ea.com | P: /
Cookie: __utmb:82955028.3.10.1541885832 | D:.signin.ea.com | P: /
Cookie: utag_main:v_id:0166ff8ea9e20017682fd993dfe50007201ae06a00bd0$_sn:1$_ss:0$_pn:3%3Bexp-session$_st:1541887651667$ses_id:1541885831650%3Bexp-session | D:.ea.com | P: /
Cookie: isPhone:false | D:signin.ea.com | P: /
Cookie: isPogo:false | D:signin.ea.com | P: /
Cookie: webun:"kelciouskm@gmail.com" | D:signin.ea.com | P: /
Cookie: __utmt:1 | D:.signin.ea.com | P: /
Cookie: __utmz:82955028.1541885832.1.1.utmcsr=easports.com|utmccn=(referral)|utmcmd=referral|utmcct=/fifa/ultimate-team/web-app/ | D:.signin.ea.com | P: /
Cookie: __utmc:82955028 | D:.signin.ea.com | P: /
Cookie: __utma:82955028.925854092.1541885832.1541885832.1541885832.1 | D:.signin.ea.com | P: /
Cookie: _gid:GA1.2.1507328639.1541885832 | D:.ea.com | P: /
Cookie: _ga:GA1.2.925854092.1541885832 | D:.ea.com | P: /
Cookie: _gat:1 | D:.easports.com | P: /
Cookie: _ga:GA1.2.1342343516.1541885820 | D:.easports.com | P: /
Cookie: JSESSIONID:EF778965535E869647A08A4C8968CF6A.prdaccountc-32 | D:signin.ea.com | P: /p
Cookie: remid:TUU6S1Zld2ZKV0tMd1dLT2NGSGdxenZMSHFSajhWSXdQb1NmSE8wanFGOToxMTEwMTYxOTQ.LA7jxyC3qSNtQQ4M0TgTX27QuzYHDS3Mi1egtB1s | D:accounts.ea.com | P: /connect
Cookie: sid:U2t6U1VZN1o1blA5WktwakJDZDZlRWszSmR2S3hLdDVNVjVNVGtZRFM5aXFvQjNPOWhuMHE4R2JiNTdIaQ.Dmna08bQUSWTe4Tw2TNXEHrXMVs3h-OsdXIQZzWH5z4 | D:accounts.ea.com | P: /connect
Version: 1.6
Search .......

**Comment by galodoido794** [comment]
Yes, that is the cause of the problem. First you have to have access to WebApp. For this you need to play Ultimate Team
