### ISSUE TITLE
Do you check version of futbin player before buying?

### ISSUE THREAD

**Issue by VatsaPatel** [galodoido794/AUTOBOT_FIFAX#23]
Do you check version of futbin player before buying?

**Comment by galodoido794** [comment]
I use FutBin to fetch some player data.
The problem is that the same player can appear with different quality.

**Comment by VatsaPatel** [comment]
Because selecting special card from futbin & then searching for gold doesn't work.

**Comment by VatsaPatel** [comment]
So is only the version of futbin bought? eg- only 88 rated & not 89 rated

**Comment by galodoido794** [comment]
[en-US]
I will not dedicate to the BOT to verify this. I'm working on another BOT (for something else).

[pt-BR]
Não vou dedicar ao BOT para verificar isso. Estou trabalhando em outro BOT (para outra coisa).

**Comment by VatsaPatel** [comment]
@galodoido794 , If possible can you share source code, maybe I can contribute in free time.
