### ISSUE TITLE
problem fifa bot

### ISSUE THREAD

**Issue by houston96** [galodoido794/AUTOBOT_FIFAX#25]
help me, i have problem with fifa LOG, check photo
![Screenshot_1](https://user-images.githubusercontent.com/48368392/54058680-487b0b00-41ff-11e9-98ce-9448f8a82fc8.png)
![Screenshot_2](https://user-images.githubusercontent.com/48368392/54058681-487b0b00-41ff-11e9-98ac-08aa66354340.png)

**Comment by houston96** [comment]
PS: I have netframe work..4.7.1.....installed and dont work this LOG.....help me please..

**Comment by galodoido794** [comment]
OK. Forget the ... Log.exe
What is the problem with AUTOBOT_FIFAX.exe?
