### ISSUE TITLE
Newtonsoft.json?

### ISSUE THREAD

**Issue by josle94** [galodoido794/AUTOBOT_FIFAX#26]
![image](https://user-images.githubusercontent.com/48806979/54779399-5bd2a100-4c17-11e9-9976-f809f9da8d69.png)

![image](https://user-images.githubusercontent.com/48806979/54779427-6f7e0780-4c17-11e9-9e51-1d34fb746fbe.png)

Can't figure these out!

**Comment by galodoido794** [comment]
You have installed: [.NET 4.7.1] (https://www.microsoft.com/net/download/dotnet-framework-runtime/net471) ??
