### ISSUE TITLE
Bug in buyer

### ISSUE THREAD

**Issue by pedrohrqe** [galodoido794/AUTOBOT_FIFAX#27]
How to fix? ![Captura de Tela (1)](https://user-images.githubusercontent.com/36456794/54882969-8f434480-4e3e-11e9-90b9-e88d1d2d891a.png)

**Comment by galodoido794** [comment]
You are using version 1.10. Try using version 1.11 

https://github.com/galodoido794/AUTOBOT_FIFAX/releases/download/1.11/AUTOBOT_FIFAXv_1_11.7z

**Comment by pedrohrqe** [comment]
I already tried using 1.11, but it did not. My account is Brazilian, I think it's something with the fut server, because when I used vpn it worked. Could you help me use my country's server?

**Comment by galodoido794** [comment]
Estranho porque utilizo aqui no Brasil e funciona e 30% dos usuários também são do Brasil.
Você já tentou alterar o Server na aba Problem?

**Comment by pedrohrqe** [comment]
Na verdade, já alterei, só funciona em um dos dois que tem. Ultimamente não está conseguindo comprar quase nada, coloco 500 buscas, de "mei pra mc" por exemplo, e pega uns 4. Não sei porque, acho que não é minha conta, pois já testei em outras 2, não sei o que pode ser.

**Comment by galodoido794** [comment]
Difícil eu imaginar o q pode ser já q funciona para a maioria.
