### ISSUE TITLE
Object reference is not set to an instance of an object.

### ISSUE THREAD

**Issue by koolkid69er** [galodoido794/AUTOBOT_FIFAX#3]
When searching for players I get a little popup saying "object reference is not set to an instance of an object. I am not sure how to fix this, please help.

Here is the image:
https://user-images.githubusercontent.com/44890137/48307799-0ae7d780-e5a9-11e8-92a7-777b7b7e70f6.PNG

**Comment by galodoido794** [comment]
Which version? Does it happen in any search?

**Comment by koolkid69er** [comment]
v1.6. and yes

**Comment by galodoido794** [comment]
In version 1.5 also this error occurs?

**Comment by galodoido794** [comment]
Maybe version 1.7 will solve this, but now I will not make it available anymore.
In case you want to send an email to galodoido794@gmail.com
