### ISSUE TITLE
Assembly error

### ISSUE THREAD

**Issue by RiderKost** [galodoido794/AUTOBOT_FIFAX#30]

**Comment by RiderKost** [comment]
Error: Impossible de charger le fichier ou l'assembly 'CefSharp.WinForms, Version=69.0.0.0, Culture=neutral, PlubicKeyToken=40c4b6fc221f4138' ou une de ses dépendances. La définition trouvée du manifeste de l'assembly ne correspond pas à la référence de l'assembly. (Exception de HRESULT : 0x80131040)

**Comment by galodoido794** [comment]
Requirements (before use install)
    https://www.microsoft.com/net/download/dotnet-framework-runtime/net471

[vc_redist.x86.exe](    https://aka.ms/vs/15/release/vc_redist.x86.exe)

    Is your Chrome up to date? Check and update anything to use version

**Comment by galodoido794** [comment]
BETA (Fifa 2020): https://github.com/galodoido794/AUTOBOT_FIFAX/releases/download/20.0.8/com.galodoido794.futauto.apk
