### ISSUE TITLE
CefSharp

### ISSUE THREAD

**Issue by KilosPL** [galodoido794/AUTOBOT_FIFAX#31]
Hi,
I have a problem with CefSharp file when I want to turn on AutoBot. What am I supposed to do? I can add that older version was working very fine

**Comment by RoyFIFAxD** [comment]
Me to i need help either

**Comment by galodoido794** [comment]
Try this:

Requirements (before use install)
[Net 4.7.1](https://www.microsoft.com/net/download/dotnet-framework-runtime/net471)

[vc_redist.x86.exe](https://aka.ms/vs/15/release/vc_redist.x86.exe)

**Is your Chrome up to date? Check and update anything to use version**

**Comment by KilosPL** [comment]
I already have these programmes and updated Chrome. It still doesnt work :(

**Comment by galodoido794** [comment]
Where is the error image?

**Comment by KilosPL** [comment]
I'm sending you photos from Autobot on WebApp (It's probably a random error) and photo from Autobot_LOG which has an error that didn't appear in older versions.
![Error1](https://user-images.githubusercontent.com/46895536/56568967-5c64ab80-65b8-11e9-9dd8-b959fac80526.PNG)
![Error2](https://user-images.githubusercontent.com/46895536/56568982-64245000-65b8-11e9-8300-095b7fdf62a2.PNG)
![Error3](https://user-images.githubusercontent.com/46895536/56568983-64245000-65b8-11e9-9830-bf594eae99aa.PNG)
These last two are from LOG and it's in Polish so I can try to translate it if it will help

**Comment by galodoido794** [comment]
Do not use AutoBot_LOG.
I think your problem may be the server. Have you tried changing the server (in the Problem Tab)?

**Comment by KilosPL** [comment]
Still nothing dude 😓

**Comment by galodoido794** [comment]
By the BOT you can access the market?

**Comment by galodoido794** [comment]
I'll check

**Comment by galodoido794** [comment]
your case is different from the others. This version 1.12 is to solve another problem:

[AUTOBOT_FIFAXv_1_12.7z](https://github.com/galodoido794/AUTOBOT_FIFAX/releases/download/1.12/AUTOBOT_FIFAXv_1_12.7z)

**Comment by KilosPL** [comment]
Sorry for not answering that long, but i thought that nothing will help.
Now it's working! Thank you, dude! I love you

**Comment by galodoido794** [comment]
BETA (Fifa 2020): https://github.com/galodoido794/AUTOBOT_FIFAX/releases/download/20.0.8/com.galodoido794.futauto.apk
