### ISSUE TITLE
object reference

### ISSUE THREAD

**Issue by Nikeliss** [galodoido794/AUTOBOT_FIFAX#32]
tried to buy on 1,11 and 1.10 versions. both says object reference is not set, what to do?

**Comment by Mimmo9797** [comment]
me too, yesterdey work.
today no

**Comment by Nikeliss** [comment]
Same :/

**Comment by Pako1993** [comment]
E' da stamattina che il bot mi da errore istanza di oggetto non impostata su un oggetto, come si risolve ?

**Comment by yasssseer6373** [comment]
Me toooo , the bot is detected by antivirus and says object reference is not set

**Comment by IceColdDi** [comment]
Same shit any solusions ??

**Comment by Pako1993** [comment]
risolto?

**Comment by Pako1993** [comment]
help

**Comment by galodoido794** [comment]
Two possibilities:
1) Antivirus is blocking the BOT
2) Changed the way to search the Ultimate Team

Try to put the BOT in another folder and clear the cache of Chrome

**Comment by yasssseer6373** [comment]
Even i disable the antivirus .. keep saying the same

Obtenez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Galo <notifications@github.com>
Envoyé : Thursday, April 25, 2019 12:23:45 AM
À : galodoido794/AUTOBOT_FIFAX
Cc : yasssseer6373; Comment
Objet : Re: [galodoido794/AUTOBOT_FIFAX] object reference (#32)


Two possibilities:

  1.  Antivirus is blocking the BOT
  2.  Changed the way to search the Ultimate Team

Try to put the BOT in another folder and clear the cache of Chrome

**Comment by RoyFIFAxD** [comment]
Help please we need it

**Comment by Pako1993** [comment]
nemmeno oggi funziona

**Comment by Vorsah** [comment]
@galodoido794


I tried your solution. I disabled my antivirus, deleted Chrome Cache, changed folder & folder path, and I downloaded the bot again. It works nothing. 

My question is now whether the bot works for you? Maybe something has changed in general EA.

German greets

**Comment by IceColdDi** [comment]
Anyone bot still work with no problems ???

**Comment by yasssseer6373** [comment]
Stiill doontttt woooorrrkkkk ... sooluuutiooonn !!!!

Obtenez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : IceColdDi <notifications@github.com>
Envoyé : Thursday, April 25, 2019 4:52:28 PM
À : galodoido794/AUTOBOT_FIFAX
Cc : yasssseer6373; Comment
Objet : Re: [galodoido794/AUTOBOT_FIFAX] object reference (#32)


Anyone bot still work with no problems ???

**Comment by yasssseer6373** [comment]
Whatt happeeen? Its not work at allllll

Obtenez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : yasseer lammm
Envoyé : Thursday, April 25, 2019 7:43:42 PM
À : galodoido794/AUTOBOT_FIFAX; galodoido794/AUTOBOT_FIFAX
Cc : Comment
Objet : Re: [galodoido794/AUTOBOT_FIFAX] object reference (#32)

Stiill doontttt woooorrrkkkk ... sooluuutiooonn !!!!

Obtenez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : IceColdDi <notifications@github.com>
Envoyé : Thursday, April 25, 2019 4:52:28 PM
À : galodoido794/AUTOBOT_FIFAX
Cc : yasssseer6373; Comment
Objet : Re: [galodoido794/AUTOBOT_FIFAX] object reference (#32)


Anyone bot still work with no problems ???

**Comment by Pako1993** [comment]
ci aiutate??????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????

**Comment by Pako1993** [comment]
soluzioni

**Comment by Pako1993** [comment]
?

**Comment by Pako1993** [comment]
rispondete

**Comment by Pako1993** [comment]
> Due possibilità:
> 
> 1. L'antivirus sta bloccando il BOT
> 2. Modificato il modo di cercare il Team Ultimate
> 
> Prova a mettere il BOT in un'altra cartella e svuota la cache di Chrome

nulla. Soluzioni?

**Comment by yasssseer6373** [comment]
Still dont work

Obtenez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Pako1993 <notifications@github.com>
Envoyé : Saturday, April 27, 2019 1:42:26 PM
À : galodoido794/AUTOBOT_FIFAX
Cc : yasssseer6373; Comment
Objet : Re: [galodoido794/AUTOBOT_FIFAX] object reference (#32)


Due possibilità:

  1.  L'antivirus sta bloccando il BOT
  2.  Modificato il modo di cercare il Team Ultimate

Prova a mettere il BOT in un'altra cartella e svuota la cache di Chrome

nulla. Soluzioni?

**Comment by galodoido794** [comment]
Okay. I went to test my BOT and this problem is really happening.
I'll check

**Comment by yasssseer6373** [comment]
Yes pls fix it .. we need the bot .. its amazing

Obtenez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Galo <notifications@github.com>
Envoyé : Sunday, April 28, 2019 11:37:54 PM
À : galodoido794/AUTOBOT_FIFAX
Cc : yasssseer6373; Comment
Objet : Re: [galodoido794/AUTOBOT_FIFAX] object reference (#32)


Okay. I went to test my BOT and this problem is really happening.
I'll check

**Comment by galodoido794** [comment]
[AUTOBOT_FIFAXv_1_12.7z](https://github.com/galodoido794/AUTOBOT_FIFAX/releases/download/1.12/AUTOBOT_FIFAXv_1_12.7z)

**Comment by yasssseer6373** [comment]
Oh thanks so much .. its works nooowwwwww

Obtenez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Galo <notifications@github.com>
Envoyé : Monday, April 29, 2019 12:13:57 AM
À : galodoido794/AUTOBOT_FIFAX
Cc : yasssseer6373; Comment
Objet : Re: [galodoido794/AUTOBOT_FIFAX] object reference (#32)


AUTOBOT_FIFAXv_1_12.7z<https://github.com/galodoido794/AUTOBOT_FIFAX/releases/download/1.12/AUTOBOT_FIFAXv_1_12.7z>

**Comment by galodoido794** [comment]
[Patreon ](https://www.patreon.com/galodoido) .... lol
=D

**Comment by Pako1993** [comment]
grazie mille <3

**Comment by Danieljj8h** [comment]
@galodoido794 , atleticano? kkk

**Comment by galodoido794** [comment]
Aqui é [Galo ](http://www.atletico.com.br) hehehehe

Thread is closed

**Comment by yasssseer6373** [comment]
Galo pls tell me how i can buy fitness?

Obtenez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Galo <notifications@github.com>
Envoyé : Wednesday, May 1, 2019 2:06:29 PM
À : galodoido794/AUTOBOT_FIFAX
Cc : yasssseer6373; Comment
Objet : Re: [galodoido794/AUTOBOT_FIFAX] object reference (#32)


Aqui é Galo <www.atletico.com.br> hehehehe

Thread is closed

**Comment by galodoido794** [comment]
BETA (Fifa 2020): https://github.com/galodoido794/AUTOBOT_FIFAX/releases/download/20.0.8/com.galodoido794.futauto.apk
