### ISSUE TITLE
riferimento all'oggetto

### ISSUE THREAD

**Issue by Pako1993** [galodoido794/AUTOBOT_FIFAX#33]
sono ormai due giorni che non si riesce a far funzionare autobotfifax. Riuscite a trovare una soluzione? almeno a risponderci. grazie

**Comment by galodoido794** [comment]
Okay. I went to test my BOT and this problem is really happening.
I'll check

**Comment by galodoido794** [comment]
BETA (Fifa 2020): https://github.com/galodoido794/AUTOBOT_FIFAX/releases/download/20.0.8/com.galodoido794.futauto.apk
