### ISSUE TITLE
riferimento oggetto

### ISSUE THREAD

**Issue by Pako1993** [galodoido794/AUTOBOT_FIFAX#34]
perchè non rispondete ???? sapete almeno dirci se il bot è completamente  rotto oppure occorre del tempo x ripararlo????

**Comment by Vorsah** [comment]
@Pako1993 pls dont spam all the time.
Not everyone has time 24 hours a day.

**Comment by Pako1993** [comment]
Ma se non funziona da 5 giorni. Vorrei solo sapere se esistono soluzioni oppure no. Basta una sola risposta.

**Comment by Mimmo9797** [comment]
Stessa cosa anche a me pako...

**Comment by galodoido794** [comment]
BETA (Fifa 2020): https://github.com/galodoido794/AUTOBOT_FIFAX/releases/download/20.0.8/com.galodoido794.futauto.apk
