### ISSUE TITLE
Ps4 and Xbox

### ISSUE THREAD

**Issue by Nikeliss** [galodoido794/AUTOBOT_FIFAX#35]
Hello, wanted to ask where problem can be, when i log into xbox acc everything works fine
when i log in ps4 it says error

**Comment by Nikeliss** [comment]
Everything works, changhed server

**Comment by galodoido794** [comment]
=D

Closed

**Comment by galodoido794** [comment]
BETA (Fifa 2020): https://github.com/galodoido794/AUTOBOT_FIFAX/releases/download/20.0.8/com.galodoido794.futauto.apk
