### ISSUE TITLE
AUTOBOT v.12 ps4 error, help me

### ISSUE THREAD

**Issue by houston96** [galodoido794/AUTOBOT_FIFAX#36]
Hi bro, help me with that problem, i make first step with clear cache and no function.. and...Application Manifest no function, watch at photo.. is installed netframework 4,7.1 and dotnet-framework-runtime...but no function..
![Screenshot_1](https://user-images.githubusercontent.com/48368392/57525595-d5436180-7333-11e9-82bb-c28d4eb3f2fe.png)
![Screenshot_2](https://user-images.githubusercontent.com/48368392/57525596-d5436180-7333-11e9-8a6f-6e6f3c8bdbec.png)

**Comment by galodoido794** [comment]
Try to do the following:

    Tab Problem
    Alter Server (change and send search)
    Maybe this will solve

**Comment by houston96** [comment]
Solved! Thank you.

**Comment by lollonigno** [comment]
i dont understand what should i do with this error, im on pc

**Comment by galodoido794** [comment]
Working to make a new robot for Fifa2020

**Comment by galodoido794** [comment]
BETA (Fifa 2020): https://github.com/galodoido794/AUTOBOT_FIFAX/releases/download/20.0.8/com.galodoido794.futauto.apk
