### ISSUE TITLE
saying " error: could not load file or assembly 'cefsharp.core.dll' or one of its dependencies . the specified module could not be found 

### ISSUE THREAD

**Issue by fgfrosted** [galodoido794/AUTOBOT_FIFAX#37]

**Comment by galodoido794** [comment]
Requirements (before use install)

    https://www.microsoft.com/net/download/dotnet-framework-runtime/net471

    https://aka.ms/vs/15/release/vc_redist.x86.exe

**Is your Chrome up to date? Check and update anything to use version**

https://github.com/galodoido794/AUTOBOT_FIFAX/releases/download/1.12/AUTOBOT_FIFAXv_1_12.7z

**Comment by galodoido794** [comment]
Working to make a new robot for Fifa2020

**Comment by galodoido794** [comment]
BETA (Fifa 2020): https://github.com/galodoido794/AUTOBOT_FIFAX/releases/download/20.0.8/com.galodoido794.futauto.apk

**Comment by fgfrosted** [comment]
Will this work if u haven’t unlocked market on web app ?

Sent from my iPhone

On 1 Oct 2019, at 04:07, Galo <notifications@github.com<mailto:notifications@github.com>> wrote:


BETA (Fifa 2020): https://github.com/galodoido794/AUTOBOT_FIFAX/releases/download/20.0.8/com.galodoido794.futauto.apk
