### ISSUE TITLE
non mi fa offrire a nessun giocatore.

### ISSUE THREAD

**Issue by gaeray** [galodoido794/AUTOBOT_FIFAX#38]
Salve, ogni volta che cerco di offrire su un giocatore non succede nulla. Non mi fa offrire e nè acquistare al compra ora. Di conseguenza il bot non mi acquista nessuno. Sapete dirmi perchè?

**Comment by galodoido794** [comment]
Working to make a new robot for **Fifa2020**

**Comment by galodoido794** [comment]
BETA (Fifa 2020): https://github.com/galodoido794/AUTOBOT_FIFAX/releases/download/20.0.8/com.galodoido794.futauto.apk
