### ISSUE TITLE
not an issue just question

### ISSUE THREAD

**Issue by Nikeliss** [galodoido794/AUTOBOT_FIFAX#39]
can i use it on pc?

**Comment by galodoido794** [comment]
Maybe with an Android PC emulator

Em segunda-feira, 30 de setembro de 2019, Nikeliss <notifications@github.com>
escreveu:
> can i use it on pc?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci6.googleusercontent.com/proxy/NFMz-IGksydIV7urQtxPLUDk0bUu1eGYaK0JQV5vG86zfvAocEBJFwLVDmmuAXRem8_YGzUTE0tNC4FAOHPNyb_Og_ABcYUM0OJf3W0K-UryCKJ6sDil83ArdnyZQyZmyqaxnEmdnaQupZKxxjJnO74XWUvcymAQ6sUOoWCa_d4cdZdAsY0RNsiTr-FMjL2pL6ggRNdqOnOcKFzbvek3UucMJAQ=s0-d-e1-ft#https://github.com/notifications/beacon/AAJSV2NJZ43HYNYL3PENJ7TQMG4UBA5CNFSM4I3X6L42YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HOPQCGQ.gif>

**Comment by galodoido794** [comment]
Maybe with an Android PC emulator

**Comment by Nikeliss** [comment]
And when it will be available?

**Comment by galodoido794** [comment]
Now it depends on Google release (Maybe today)

**Comment by at1x77x** [comment]
When the bot will be available pls ?

**Comment by galodoido794** [comment]
I'm waiting for Google to release

**Comment by at1x77x** [comment]
Today or an other day ?

**Comment by galodoido794** [comment]
It only depends on Google. I hope it is today

**Comment by at1x77x** [comment]
Ok thx

**Comment by galodoido794** [comment]
BETA: https://github.com/galodoido794/AUTOBOT_FIFAX/releases/download/20.0.8/com.galodoido794.futauto.apk

**Comment by galodoido794** [comment]
https://autobotfifax.blogspot.com/2019/10/run-futauto-with-emulator-android.html
