### ISSUE TITLE
"Are you logged into fifa" issue v1_8

### ISSUE THREAD

**Issue by DanteFifa22** [galodoido794/AUTOBOT_FIFAX#4]
Hey, i tried search a few player and chemistry styles, all without success. already reset my pc and cleaned my browser, but the "are you logged into fifa" error keep occurring.

Ps: Version 1_3 is working fine .
Ps2: South america region.

Edit1: windows 10 user

**Comment by galodoido794** [comment]
Run AUTOBOT_LOG.exe and send me the Log.txt

**Comment by DanteFifa22** [comment]
[_LOG_FIFA.txt](https://github.com/galodoido794/AUTOBOT_FIFAX/files/2612302/_LOG_FIFA.txt)

Before play search Log.txt

**Comment by DanteFifa22** [comment]
[_LOG_FIFA.txt](https://github.com/galodoido794/AUTOBOT_FIFAX/files/2612305/_LOG_FIFA.txt)

 After play Search

**Comment by galodoido794** [comment]
First case of this.
Is the date and time of windows correct?

Em sáb, 24 de nov de 2018 às 12:04, DanteFifa22 <notifications@github.com>
escreveu:

**Comment by DanteFifa22** [comment]
i believe so, its all original

**Comment by galodoido794** [comment]
Check your email of Hotmail ...

**Comment by DanteFifa22** [comment]
dantewk10@hotmail.com

**Comment by mansurjon123** [comment]
galodoido794 thank you for soft.
I choose a player Reus 87 CAM TOTW special card for the amount of 350,000, the program buys me Reus 86 LF UCL card for 170,000 ((((
I think you can fix it.

**Comment by galodoido794** [comment]
> galodoido794 thank you for soft.
> I choose a player Reus 87 CAM TOTW special card for the amount of 350,000, the program buys me Reus 86 LF UCL card for 170,000 ((((
> I think you can fix it.

Version 1.8?

**Comment by mansurjon123** [comment]
yes 1.8

**Comment by galodoido794** [comment]
> yes 1.8

I do not know if BOT knows how to differentiate TOTW and UCL.
BOT knows how to differentiate Gold with Special.

I have to think how to make that difference (TOTW and UCL)

**Comment by DanteFifa22** [comment]
Hey, i re installed, reset my pc and cleaned my broswer again and has fixed the problem, thanks for the help, the software is amazing btw

**Comment by galodoido794** [comment]
=D 
LIKE YOUTUBE ...

**Comment by galodoido794** [comment]
[en-Us]
I would like to dedicate more time to the BOT, create new features, improve
support or create new BOTS (for other games).
If you're interested, I've created a campaign (
https://www.patreon.com/galodoido), but do not worry it's not required.

[Pt-br]
Gostaria de dedicar mais tempo ao BOT, criar novas funcionalidades,
aprimorar o suporte ou criar novos BOTS (para outros jogos).
Se tiver interesse criei um campanha (https://www.patreon.com/galodoido),
mas não se preocupe que não é obrigatório.

Em sáb, 24 de nov de 2018 às 12:40, DanteFifa22 <notifications@github.com>
escreveu:
