### ISSUE TITLE
how do i get this on pc ?

### ISSUE THREAD

**Issue by frostedfc** [galodoido794/AUTOBOT_FIFAX#40]

**Comment by galodoido794** [comment]
I am researching a way to convert the apk into a Windows executable. Another way is to find a compatible Android emulator

**Comment by frostedfc** [comment]
Are u trying to make it like the way it was last year 
Ps I appreciate what you do man got a lot of respect for you !

**Comment by galodoido794** [comment]
https://autobotfifax.blogspot.com/2019/10/run-futauto-with-emulator-android.html

**Comment by frostedfc** [comment]
Hello , how do u “rotate screen” on the windows emualator

**Comment by galodoido794** [comment]
Search in google: "nox" rotate screen android

Em ter., 12 de nov. de 2019 às 16:29, frostedfc <notifications@github.com>
escreveu:

> Hello , how do u “rotate screen” on the windows emualator
>
> Sent from my iPhone
>

**Comment by frostedfc** [comment]
Hello , if I subscribe to patreon can I can get last years menus but for Fifa 20 ?

**Comment by frostedfc** [comment]
Hello can u send me the link for the fifa 19 auto buyer ?

**Comment by galodoido794** [comment]
FIFA 2019 => I no longer have and do not recommend using it for reasons of
account security and banning from EA

Em dom., 19 de jan. de 2020 às 13:23, frostedfc <notifications@github.com>
escreveu:

> Hello can u send me the link for the fifa 19 auto buyer ?
>
> Sent from my iPhone
>

**Comment by frostedfc** [comment]
Hi how do I fix error : you are temporarily out of the market go and play and stop using the market

**Comment by frostedfc** [comment]
Are you making an auto buyer for Fifa 21 ?

**Comment by galodoido794** [comment]
https://github.com/galodoido794/AUTOBOT_FIFAX/issues/74
