### ISSUE TITLE
Browser do Blue Stacks

### ISSUE THREAD

**Issue by GustavoFurtad0** [galodoido794/AUTOBOT_FIFAX#41]
O app não abre no blue stacks, fala que o browser não é compatível com o aplicativo

**Comment by galodoido794** [comment]
Testa com outros emuladores (deve ter uns 10). Agora não consigo testar os emuladores pra te falar um que funciona

**Comment by galodoido794** [comment]
I'll see if I can fix the Android 5 issue (browser error) by Sunday.

Install from Google play to help me and get updates.
https://play.google.com/store/apps/details?id=com.galodoido794.futauto

**Comment by galodoido794** [comment]
Conseguiu algum emulador? Se não vou tentar verificar uma maneira no final
de semana,

Em quarta-feira, 2 de outubro de 2019, GustavoFurtad0 <
notifications@github.com> escreveu:
> Closed #41.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci6.googleusercontent.com/proxy/AmKoNa5X7a6AKRwUYg7qIkUuCrdD_osECSn5y_S4ujbBJVWSCAh_WfTng5pTmZ6RWecjQ4p3e0V_wUjkGhUeMAnBdVCSrLK8LAlU67WyL4klS7Nrxas_m7kO657PZcJjQpCPA-XsRQxXCBU7FnhukPD78XK2Y86B9Ite_cVlVx0Q9sIuXWvb2PEIy4nYLPfnwp9vqVlnmuKJvKxN7TzrFBckewVxF3G5rLdq3XdfU_god8fgf3ZfKDyX86pbAbI=s0-d-e1-ft#https://github.com/notifications/beacon/AAJSV2K2ZLVSNRQ72MBRDCLQMVFNBA5CNFSM4I4OBKD2YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOT7SDQPQ.gif>

**Comment by galodoido794** [comment]
https://autobotfifax.blogspot.com/2019/10/run-futauto-with-emulator-android.html
