### ISSUE TITLE
Samsung Note 3 

### ISSUE THREAD

**Issue by conduct10** [galodoido794/AUTOBOT_FIFAX#42]
When i open app it says browser not compatible , on my samsung note 3.

**Comment by galodoido794** [comment]
What version of Android?

**Comment by conduct10** [comment]
5.0

**Comment by galodoido794** [comment]
I'll see if I can fix the Android 5 issue (browser error) by Sunday.

**Comment by galodoido794** [comment]
I'll see if I can fix the Android 5 issue (browser error) by Sunday.

Install from Google play to help me and get updates.
https://play.google.com/store/apps/details?id=com.galodoido794.futauto

**Comment by galodoido794** [comment]
https://autobotfifax.blogspot.com/2019/10/run-futauto-with-emulator-android.html
