### ISSUE TITLE
I think theres problem

### ISSUE THREAD

**Issue by Nikeliss** [galodoido794/AUTOBOT_FIFAX#44]
Hi, I downloaded emulator for android apps and bot worked yesterday, but today it didnt get me anything, so I went to web on bot and tried bid or buy something but it wont let me do that, firstly thought of ban, because of too many actions, but when i go to web on normal app, everything works.. what it could be?

**Comment by galodoido794** [comment]
1) Which emulator did you use?
2) Can you access the market in the emulator (Tab Web)?
3) Any errors occur?

**Comment by Vorsah** [comment]
It is a softban from EA, In a few Hour you can bid again of player & the bot works.

**Comment by galodoido794** [comment]
No APP does not work, but on the Web does it work?

**Comment by Vorsah** [comment]
It is a problem from both, APK & Web App. But it is a problem from EA and not from your Bot.

**Comment by Vorsah** [comment]
![pic](https://user-images.githubusercontent.com/45430693/66259698-679d4380-e7b4-11e9-8cd3-45400befa8b2.PNG)

**Comment by galodoido794** [comment]
1) How many requirements did you make on the day? or in total? An estimate ...
2) Was it using an external server or your cellphone yourself?
3) Do you use the account to buy and sell or play it too?
