### ISSUE TITLE
Is old bot safe to use

### ISSUE THREAD

**Issue by Nikeliss** [galodoido794/AUTOBOT_FIFAX#45]
As old bot is working is it safe to use?

**Comment by galodoido794** [comment]
Every BOT has its risk, but the risk is controlled by the user. 

Avoid making more than 3000 requests per day, do not BOT while playing, do not use the account only to buy and sell.

**Comment by galodoido794** [comment]
A lot of people using it, but few made evaluation. I need a good review of the app (on Google Play) to keep putting new features.

https://play.google.com/store/apps/details?id=com.galodoido794.futauto
