### ISSUE TITLE
Why kaspersky found identity theft !? (http://tharbadir.com/2?z=2582793)

### ISSUE THREAD

**Issue by SimonPetrus** [galodoido794/AUTOBOT_FIFAX#46]
09.10.2019 21.38.19;Dangerous URL blocked;http://tharbadir.com/2?z=2582793;http://tharbadir.com/2?z=2582793;URL phishing URLs are listed in the database;AUTOBOT_FIFAX;10/09/2019 21:38:19

**Comment by galodoido794** [comment]
**AutoBot 2019** has not been updated for a long time.
Therefore, do not use it anymore for safety reasons.

Importantly, no user data is collected. Only the **EA** that collects

Now use FutAUTO 2020

**Comment by SimonPetrus** [comment]
but I don't have an android device. I'm using iphone
