### ISSUE TITLE
ios & pc

### ISSUE THREAD

**Issue by SimonPetrus** [galodoido794/AUTOBOT_FIFAX#47]
but I don't have an android device. I'm using iphone

**Comment by galodoido794** [comment]
I am researching some Android emulators for Windows that the APP works.

**Comment by SimonPetrus** [comment]
I'm waiting for your advice

**Comment by SimonPetrus** [comment]
Do you make an app for iphone?

**Comment by SimonPetrus** [comment]
App store or ipa file

**Comment by galodoido794** [comment]
Apple does not encourage programmers (with little money).
The publication in the store is another hinter, they are very annoying.
This APP at the Apple Store has a great chance of being recursed.

**Comment by SimonPetrus** [comment]
:s ok . Do you add filters to the program? (League,position etc)

**Comment by galodoido794** [comment]
Today is divided into Consumables and Players (more or less following the Fut Web App)
Now if you are talking about putting more filters for players (in the future) 
I think it will be difficult. 
The first version will be looking for a specific player given their rarity (Idol, UC, etc)

**Comment by conduct10** [comment]
Did you fix the android 5.0 incompatible issue bro ?

**Comment by galodoido794** [comment]
I have an Android 5 phone and had no problem in the previous version and the current version.

Now if you're talking about android emulator, I really don't know why it doesn't work.

**Comment by galodoido794** [comment]
https://autobotfifax.blogspot.com/2019/10/run-futauto-with-emulator-android.html

**Comment by SimonPetrus** [comment]
Unsupported browser error how to fix this ?

**Comment by SimonPetrus** [comment]
im try emulator and samsung tablet

**Comment by galodoido794** [comment]
Did not work?

https://autobotfifax.blogspot.com/2019/10/run-futauto-with-emulator-android.html

Em dom, 13 de out de 2019 às 11:16, SimonPetrus <notifications@github.com>
escreveu:

**Comment by galodoido794** [comment]
A lot of people using it, but few made evaluation. I need a good review of the app (on Google Play) to keep putting new features.

https://play.google.com/store/apps/details?id=com.galodoido794.futauto
