### ISSUE TITLE
When i go to buy players it doesnt buy any like if i went to buy a son for 23k even though he sells for 22k it still doesnt let me buy him

### ISSUE THREAD

**Issue by frostedfc** [galodoido794/AUTOBOT_FIFAX#5]

**Comment by galodoido794** [comment]
I'll analyze what's happening.

**Comment by frostedfc** [comment]
ok thanks

**Comment by frostedfc** [comment]
now its saying are you logged into fifa

**Comment by galodoido794** [comment]
No need. I already know where the error is and I'm trying to fix it

**Comment by frostedfc** [comment]
ok thanks

**Comment by frostedfc** [comment]
how long do u think this will take

**Comment by galodoido794** [comment]
The problem is that BOT STILL does not navigate the pages. I'm thinking what I'm going to do to solve it the quickest.

**Comment by frostedfc** [comment]
i dont know what that means sorry

**Comment by frostedfc** [comment]
u fixed it yet ?

**Comment by galodoido794** [comment]
two hours (I think)

**Comment by frostedfc** [comment]
ok

**Comment by frostedfc** [comment]
can u let me know when done ?

**Comment by frostedfc** [comment]
u done bro ?

**Comment by frostedfc** [comment]
hello are you done ?

**Comment by galodoido794** [comment]
One moment ... 1 hour ... wait ..

Em sáb, 24 de nov de 2018 às 15:02, frostedfc <notifications@github.com>
escreveu:

**Comment by frostedfc** [comment]
1 more hour ?

**Comment by frostedfc** [comment]
is it working /

**Comment by frostedfc** [comment]
HOW LONG WILL IT BE !!!!

**Comment by galodoido794** [comment]
hahaha totally free and people wanting me to work fast. Hopefully I'll make version 1.9 available

**Comment by frostedfc** [comment]
WHEN will that be available ?

**Comment by galodoido794** [comment]
I'm trying to improve the search for special players. Wait ...

**Comment by frostedfc** [comment]
ok do u have an estiamted time ?

**Comment by galodoido794** [comment]
I think it's a maximum of two hours (because I'm tired and wanting to play FIFA 19)

**Comment by frostedfc** [comment]
ok thanks appreciate what u do :)

**Comment by frostedfc** [comment]
can u let me know when done ?

**Comment by galodoido794** [comment]
https://github.com/galodoido794/AUTOBOT_FIFAX/releases/download/1.9/AUTOBOT_FIFAXv_1_9.7z

**Comment by frostedfc** [comment]
thanks so much bro
