### ISSUE TITLE
Tip

### ISSUE THREAD

**Issue by aleimpa** [galodoido794/AUTOBOT_FIFAX#52]
Thank you for the fantastic app. I admire you. But there is a little problem, when I am on the "web side" of the app and I push the Samsung back botton the app closes and no longer works.

**Comment by galodoido794** [comment]
Never tested it =D
I will put in my list of corrections

**Comment by galodoido794** [comment]
A lot of people using it, but few made evaluation. I need a good review of the app (on Google Play) to keep putting new features.

https://play.google.com/store/apps/details?id=com.galodoido794.futauto
