### ISSUE TITLE
Error buy players

### ISSUE THREAD

**Issue by fran0512** [galodoido794/AUTOBOT_FIFAX#53]
When I buy a player, it is automatically sold at a random price. It has made me lose coins. Otherwise, great work with the app

**Comment by galodoido794** [comment]
random price lol ... 
What I do is put the maximum price you set. Example: I put a **maximum price of 10** and three records appeared: **12, 8, 7**. BOT tries to buy by order. In that case he will buy the **8**. 
I did not make him go through all and buy the smallest. 
However, this is not random.

**Comment by fran0512** [comment]
Hi,

I didn't mean that. When I buy a player, it is automatically put on sale with a random price.

For example:
I buy Fekir for 7000 coins and automatically put on sale for 4500 coins :(

**Comment by galodoido794** [comment]
Are you saying that BOT sold the player?

I think I know what might have happened. The bot took some parameters from TAB Consumibles. I will upload a version where I force TAB Player not to sell.

**Comment by fran0512** [comment]
Yes, exactly. I could reproduce the error and attach photo

**Comment by galodoido794** [comment]
I will upload a new version that prevents this. I believe that in an hour will be in the store

**Comment by galodoido794** [comment]
I already sent a new version to Google Play.

I need a good review of the app (on Google Play).

**Comment by fran0512** [comment]
Thank you very much. Good job.

My 5 stars you have them since the first day :)
