### ISSUE TITLE
Player

### ISSUE THREAD

**Issue by tomix632** [galodoido794/AUTOBOT_FIFAX#54]
when will the automatic listing of players be available?

**Comment by at1x77x** [comment]
?

**Comment by tomix632** [comment]
automatic exposure

**Comment by tomix632** [comment]
issuance players

**Comment by galodoido794** [comment]
I do not understand. 
Do you want the app to list the players?

**Comment by tomix632** [comment]
putting the player

**Comment by tomix632** [comment]
automatic player listing

**Comment by tomix632** [comment]
automatic selling of players

**Comment by tomix632** [comment]
because now you can only buy

**Comment by galodoido794** [comment]
As it is a feature under test, I am hoping to put the feature to sell. I believe that in 10 days will be available.

**Comment by rafaelrr08** [comment]
Tem como pesquisar jogadores por categoria,  ou seja, pesquisar mais de um em simultâneo ?
