### ISSUE TITLE
Problem with the App

### ISSUE THREAD

**Issue by Vorsah** [galodoido794/AUTOBOT_FIFAX#55]
I have a promo with the version you buy with the player.

Since this feature has been added, an error message often appears when buying consumer items. This is "Error: You are temporarily out of the market. Go play and stop using the market.".

But there is no mistake. Everything works on the web app. It does not need to be updated, internet is not gone, no one is in the account and you can bid on players. You can always, looking for the error and he continues to buy.

In the version before that, the error message does not come.

**Comment by Vorsah** [comment]
Or, Error: Your account may have a problem. Try to buy something 'manually' in the market.

**Comment by Vorsah** [comment]
I have try this Account in the current Version and this messages doesnt come.

**Comment by galodoido794** [comment]
"Error: You are temporarily out of the market. Go play and stop using the market.".

This warning is that you are making **too many requests with the same IP (usually)**. 
You can turn off your modem or your (mobile) data network to generate a new IP. 

If the error continues it is really good to stop and not risk being "detected".

**Comment by Vorsah** [comment]
Ahh okay, ty for the help.
