### ISSUE TITLE
Consumable bug

### ISSUE THREAD

**Issue by RazvYMrs** [galodoido794/AUTOBOT_FIFAX#57]
I put to buy at 5k chemstry style SHADOW. I wait ~300 searches and he didn't buy me anything.
I stopped him and I manually searched the webapp and we found 4 at 5k.
Same thing with HUNTER and CF-CAM.
Possibly the same problem as fitness??

**Comment by houston96** [comment]
I have the same problem..with that...idk, maybe all consumables bug..

**Comment by galodoido794** [comment]
Have you seen or bought it on the market manually?

I've happened to "see", but at the time of buying talk that the item is no longer to sell.

**Comment by RazvYMrs** [comment]
I know what you say, but they were available to buy. 
I bought it.

**Comment by galodoido794** [comment]
I will test today

**Comment by galodoido794** [comment]
Doing a test just bought a consumable (Plataform Xbox). However, I believe that tomorrow or Saturday I will release a new version with enhancements that "may" solve the problem that is occurring for you.

**Comment by bfernandes12** [comment]
I have the same problem too, when i started using the app about two weeks ago i bought like 30 consumables an hour, and now less of 5

**Comment by galodoido794** [comment]
I'm going to release a new version today that might solve this problem.

**Comment by galodoido794** [comment]
Which platform do you play? PS4 or Xbox?

**Comment by RazvYMrs** [comment]
PS4

**Comment by galodoido794** [comment]
ok

**Comment by galodoido794** [comment]
New Version (Waiting for Google to release)

* New Feature: Sell the Player (I tested the version and it worked)
* Search detail changed (internal change)
