### ISSUE TITLE
Hi guys, when i try to search player error "Are you logged in fifa? check" shows. When i try to search player on web app another error shows. Yesterday everything worked. Can you help?

### ISSUE THREAD

**Issue by Amrofifa** [galodoido794/AUTOBOT_FIFAX#58]
![Screenshot_20191111-144744](https://user-images.githubusercontent.com/57623755/68585497-781b9a80-0493-11ea-8319-f79ae469ca73.jpg)

**Comment by galodoido794** [comment]
This seems to be something temporary.
Try later

**Comment by Amrofifa** [comment]
Than 12 hours on the same !! , please your help :(

**Comment by Vorsah** [comment]
You used the bot way too often. This message stays up to 2 days. Then it should go again. Next time, set the search and the interval higher.

**Comment by Vorsah** [comment]
If you have too many searches on the web app every day, you will get this so-called soft spell. In any case, better than a full spell. The next time you have to take better care.

**Comment by Amrofifa** [comment]
Sure , just two days ?

**Comment by Vorsah** [comment]
maximum 2 days

**Comment by Amrofifa** [comment]
Thx alot

**Comment by galodoido794** [comment]
=D
