### ISSUE TITLE
bug search players

### ISSUE THREAD

**Issue by houston96** [galodoido794/AUTOBOT_FIFAX#59]
When i go to search one player with that autobot..on ps4 he give me "Unispected error", i restart app, dezinstall, install again...the result it's 0, but when i go on "WEB" on the transfer market... and i search one player..the web app give that
![Screenshot_1](https://user-images.githubusercontent.com/48368392/69338277-7b6d0e00-0c6b-11ea-8616-2151924e78c6.png)
Ok, i go on my PS4 on transfer list..and it's OK, no banned..so can you help me?

**Comment by galodoido794** [comment]
When something similar happens, stop using the APP market and go play for two days. Then come back and check.

**Comment by galodoido794** [comment]
https://github.com/galodoido794/AUTOBOT_FIFAX/issues/74
