### ISSUE TITLE
ads

### ISSUE THREAD

**Issue by mestro1** [galodoido794/AUTOBOT_FIFAX#60]
i get that u make the money off the ads and all, but can u make the ads autoclose so when i look at my hits it wont show a finished ad.

ps im having trouble finding a good filter for the bot and also for the player. any recommendations?

**Comment by galodoido794** [comment]
About advertising **Google** does not allow to close automatically (if it was possible I had done).

Possibly you are using the latest version. 
About player research, it will depend on the price and quality of the player. If you are unsure if the purchase is really working, search for higher priced consumables to see if you will buy.

**Comment by galodoido794** [comment]
https://github.com/galodoido794/AUTOBOT_FIFAX/issues/74
