### ISSUE TITLE
New player TOTGS

### ISSUE THREAD

**Issue by HellGrimes** [galodoido794/AUTOBOT_FIFAX#61]
Is there anyway that we can buy them in app?

**Comment by galodoido794** [comment]
Are you using NOX emulator or your android device?

If it's your device try updating Chrome and Web View.

This problem is very rare to occur.

**Comment by galodoido794** [comment]
Try the following. Set the GOLD quality and enter the correct ID and Rating. 

When it's GOLD I ignore quality and try to look for **ID** and **rating**. Maybe it works.

**Comment by HellGrimes** [comment]
Player ID?
Special cards appears 2 codes the player and other.
For bruno f.. i put 86 is code 212198 and gold? Even if im trying his TOTGS?

**Comment by galodoido794** [comment]
When you have two code, take one and play it in Google Image to see which image will appear.
You can try with TOTGS

**Comment by mestro1** [comment]
When is bidding gonna be added, cuz player sniping is kinda hard when the prices fluctuate

**Comment by galodoido794** [comment]
https://github.com/galodoido794/AUTOBOT_FIFAX/issues/74
