### ISSUE TITLE
It says unsupported browser when I start it

### ISSUE THREAD

**Issue by mestro1** [galodoido794/AUTOBOT_FIFAX#62]
How do I fix this, full guide I’m not a pro

**Comment by galodoido794** [comment]
Are you using NOX emulator or your android device?
If it's your device try updating Chrome and Web View.
This problem is very rare to occur.

**Comment by mestro1** [comment]
It’s using my android, but when I search the web app on chrome it works, but when I use ‘browser’ by android, it says unspupported. How do I make the app work on chrome and not the default browser

**Comment by galodoido794** [comment]
I don't know why this happens (on very few devices)

**Comment by galodoido794** [comment]
https://github.com/galodoido794/AUTOBOT_FIFAX/issues/74
