### ISSUE TITLE
Faster search

### ISSUE THREAD

**Issue by jonkin4435** [galodoido794/AUTOBOT_FIFAX#64]
Hi can i set faster Search in app on Android i mean 0.2 sec orfaster i know i can will get ban maybe i can change it on source code can u help me?

**Comment by galodoido794** [comment]
A very fast search will be characterized as BOT (and you will take permanent BAN), so there is the random and a "human" time.

With these intervals I use the program since 2018 and never had a problem.

**Comment by jonkin4435** [comment]
Ok bro i know i can get ban but can i Search It faster i rly want it

czw., 2 sty 2020, 12:39 użytkownik Galo <notifications@github.com> napisał:

**Comment by galodoido794** [comment]
I never put it to search faster because it's too risky.

It may occur from the server crash because it is making too many requests for minutes and you get banned in sequence.

**Comment by jonkin4435** [comment]
Can i do IT solo maybe on source code ?

czw., 2 sty 2020, 14:53 użytkownik Galo <notifications@github.com> napisał:

**Comment by jonkin4435** [comment]
Maybe u can give me a modify APK where i can set speed Search Luke 0.2-0 5
sec pls

czw., 2 sty 2020, 17:28 użytkownik Jakub Reizler <jakubreizler22@gmail.com>
napisał:

**Comment by jonkin4435** [comment]
Please, could you send me the APK mod with quick search set

czw., 2 sty 2020, 19:12 użytkownik Jakub Reizler <jakubreizler22@gmail.com>
napisał:

**Comment by galodoido794** [comment]
https://github.com/galodoido794/AUTOBOT_FIFAX/issues/74
