### ISSUE TITLE
unexpected error

### ISSUE THREAD

**Issue by ruveijj** [galodoido794/AUTOBOT_FIFAX#65]
não consigo usar o app na manhã e na tarde pois fica dando erro de unexpected error e eu não sei o que é isso, pode me ajudar?

sugestão tbm, possibilitar de snipar 2 jogadores simultaneamente

**Comment by galodoido794** [comment]
Quando ocorre esse erro você consegue navegar e compra no mercado pelo FutAUTO?

**Comment by ruveijj** [comment]
> Quando ocorre esse erro você consegue navegar e compra no mercado pelo FutAUTO?

não, fala assim: " desculpe um erro ocorreu durante você tentava completar sua pesquisa, por favor tente em outro momento"

e fica assim a tarde e a manhã inteira e não consegui pensar em nada na solução

**Comment by galodoido794** [comment]
1 ) Pela sua resposta não ficou claro para mim. Usando o mercado "normal", mas pelo FutAuto você também não consegue pesquisar e comprar?
2 ) Funcionava e parou de funcionar ou para você nunca funcionou? 
3 ) Vc esta usando emulador ou celular?
4 ) Sua conta é nova no Ultimate Team ou você já jogava antes?

**Comment by ruveijj** [comment]
sim, pelo companion (app da ea) funciona normal o mercado mas pelo futauto não, deve ser isso que não deixa snipar mas não sei por que acontece de não conseguir pesquisar

então mano, lá pelas 6:30 da tarde volta a funcionar o mercado no futauto e pela manhã umas 10 horas já para de novo e acabo tendo que esperar a tarde inteira 

celular

minha conta foi fundada em 2018 e é a primeira vez que uso um aplicativo pra ajudar a lucrar

**Comment by galodoido794** [comment]
Se vc tenta utilizar o mercado "normalmente" pelo FutAuto e não consegue, logo, não vai conseguir "snipar".

Você pelo menos consegue ver os dados da sua conta na Aba Web? Isto é, logou e colocou a autentição duas etapas e consegue acessar sua conta ... 

Se falar que consegue ver os dados da sua conta, mas não acessa o mercado então tenta desinstalar e instalar novamente. 

A data e hora do seu celular estão corretos?
Qual o modelo do seu celular?
Sua conta é PC. Xbox ou PS?

**Comment by ruveijj** [comment]
sim, consigo acessar minha conta normalmente mas dá erro no mercado quando tento fazer qualquer pesquisa desinstalar e instalar tentei 1 vez e não adiantou

minha hora e data estão corretos
xiaomi redmi note 7 ( não sei se interfere em algo já que as vezes funciona e as vezes não ) 
minha conta é ps4

**Comment by galodoido794** [comment]
Estranho porque é o primeiro relato desse comportamento.

Faz um teste. 
Quando não estiver funcionando:
1) Feche o FutAuto

2) Caso esteja utilizado Wifi no celular desligue e ligue na rede 3G\4G (porque o IP vai mudar).
2.1) Se estiver utilizar a rede 3G então desligue espere um pouco e ligue novamente (para mudar o IP)

3) Abra o FutAuto novamente e tenta navegar no mercado "normalmente" pesquisando e tentando comprar. 

Veja se assim vai funcionar ... a ideia é tentar gerar um novo IP

**Comment by ruveijj** [comment]
mano tentei da forma que você disse e não resultou, até em outro aparelho tentei e não funcionou, estranho porque no companion funciona normal e no futauto não

**Comment by ruveijj** [comment]
tava dando uma olhada no futauto e no general estatística e existe um IP lá, não sei se tem algo haver

**Comment by galodoido794** [comment]
O IP é para saber que vc estava com X e depois conseguiu alterar para Y ...

**Comment by ruveijj** [comment]
mas não consigo usar ainda o futauto. já reinstalei fiz o que dava..

**Comment by galodoido794** [comment]
Tenta deslogar do FutAuto e logar novamente. 
Isto é, vai na Aba Web e acho que no canto superior esquerdo, clica na engrenagem e Sign out.

Vc falou q pelo App do Companion funcionou, mas vc tentou pelo o Chrome no seu computador?

**Comment by ruveijj** [comment]
pelo console funciona no Chrome não tentei, relogar a conta vou tentar

**Comment by ruveijj** [comment]
tentei no companion pelo computador e não deu..

**Comment by ruveijj** [comment]
e aí? não sabe como resolver? tô com unexpected error desde de manha

**Comment by galodoido794** [comment]
Como é um caso isolado é difícil de resolver. Para que eu consiga teria que reproduzir o caso.

**Comment by galodoido794** [comment]
Mais alguém com esse erro?

**Comment by CryDie1011** [comment]
Hi! I have this problem too. The app was working perfectly, but in the afternoon has send me the same message. I can't snipe or buy anything in the market. Please, help us! I really like the app, so I want to keep using it

**Comment by CryDie1011** [comment]
I've tried everything, I've uninstalled the app, loged out, etc. But the app doesn't work, the Companion Web App works perfectly, and I can buy everything without problems

**Comment by galodoido794** [comment]
I will need an account that occurs this problem to verify. Send for: galodoido794@gmail.com

--------------------- pt-br-----------------------------
Vou precisar de uma conta que ocorre esse problema para verificar.  Enviar para: galodoido794@gmail.com

**Comment by delarajr** [comment]
Amigo, não estou conseguindo comprar jogadores. Fiz algumas simulações com jogadores baratos e não comprou. Pode fazer um vídeo explicando? Para consumíveis e entrosamento funciona bem! Obrigado desde já.

**Comment by galodoido794** [comment]
Veja esse tutorial: [Buy Player](https://autobotfifax.blogspot.com/2019/10/how-to-buy-player-with-futauto.html)

Depois disso qual é a sua dúvida?

**Comment by delarajr** [comment]
Amigo, já fiz esse tutorial e não funcionou. Já tentei com vários jogadores, inclusive coloquei o preço maior, para ver se compra rápido, e mesmo assim, não comprou nenhum. Pode testar e ver se realmente ainda está funcionando? Pode gravar a tela do celular com ele funcionando e colocar no seu canal do YouTube? Agradeço desde já.

**Comment by galodoido794** [comment]
Qual ID, rating e quality vc ta tentando comprar?

**Comment by delarajr** [comment]
Id: 237535, Rating estou usando sempre 98 e quality bronze. Valor de compra 200.
Simulei dessa forma e não funcionou.
Está correto assim?

**Comment by galodoido794** [comment]
Uma carta bronze com 98 de rating? O rating deve ser do jogador que você procura.

Exemplo:

https://www.futhead.com/20/players/497/neymar/

Neymar
Id: 190871
Rating: 92
Quality: Gold

**Comment by delarajr** [comment]
Agora entendi. Rating = Overall.
Obrigado amigo.

**Comment by Ptpain82** [comment]
Estou com o mesmo problema e quando tento pesquisar no futauto diz para tentar mais tarde porque aconteceu um erro...

**Comment by galodoido794** [comment]
Preciso uma conta de teste para simular esse erro.

**Comment by CryDie1011** [comment]
Hi! It seems that the error only hapens when the app is recently installed.
It doesn't happen anymore for me, the app is working good right now.

Pdd: you should incorporate filters to the player's search system, it would
be so good.

Tahnks man.

**Comment by Hfreitas123** [comment]
Instalei a app ha 2 dias e funcionou lindamente, mas agora sempre que tento dar snipe a jogadores/consumíveis aparece-me "Unexpected Error".
Muito obrigado pela atenção

**Comment by galodoido794** [comment]
Você usa sua conta principal ou uma conta secundária? Eu preciso de uma conta para testar esse erro (ideal que seja uma conta secundária)

**Comment by Hfreitas123** [comment]
Eu uso conta principal.
Clonei a APP no meu telemóvel e deu o mesmo erro. Vou tentar agora com outro telemóvel

**Comment by galodoido794** [comment]
O problema que isso não ocorre comigo então eu não consigo testar para saber o q está acontecendo.
Caso alguém queira pode passar os dados da conta (se possível secundária) para o meu e-mail: galodoido794@gmail.com 

Amanhã a noite (caso tenha uma conta) eu texto para ver se consigo ver o que está acontecendo.

**Comment by tugapedro82** [comment]
> O problema que isso não ocorre comigo então eu não consigo testar para saber o q está acontecendo.
> Caso alguém queira pode passar os dados da conta (se possível secundária) para o meu e-mail: [galodoido794@gmail.com](mailto:galodoido794@gmail.com)
> 
> Amanhã a noite (caso tenha uma conta) eu texto para ver se consigo ver o que está acontecendo.

Boas mais uma vez obrigado pela apk. Fiz um vídeo do erro a acontecer na procura do mercado, sendo que se procurar e não der consequentemente não dá para comprar , https://youtu.be/UqkzSzX-gqc. Sendo que precisas de uma conta para verificar podemos marcar um dia e uma hora assim que me responderes a esta mensagem e dou te o login da minha conta. Muito obrigado, adoraria participar com algum dinheiro para ajudar a desenvolver a aplicação assim que acabe esta pandemia. Abraço

**Comment by galodoido794** [comment]
I'm not checking problem or suggestion right now because of the down warning:

Because of Covid19 I'm months without updating the FutAUTO, HOWEVER I'm coming back at the end of the month (August 2020) already thinking about FIFA 2021

**Comment by galodoido794** [comment]
https://github.com/galodoido794/AUTOBOT_FIFAX/issues/74
