### ISSUE TITLE
Autobuyer de pc

### ISSUE THREAD

**Issue by Condini** [galodoido794/AUTOBOT_FIFAX#66]
Você pretende fazer algum autobuyer de pc ainda para o fifa20?

Queria saber se há alguma outra forma de contato com vc para tirar algumas dúvidas de dev

**Comment by galodoido794** [comment]
Uma versão winforms a principio não está nos meus planos. 
O que está é tentar fazer um "template de jogadores" para evitar de ficar toda hora procurando IDs.

Contato: galodoido794@gmail.com

**Comment by galodoido794** [comment]
https://github.com/galodoido794/AUTOBOT_FIFAX/issues/74
