### ISSUE TITLE
MASS BID

### ISSUE THREAD

**Issue by ruveijj** [galodoido794/AUTOBOT_FIFAX#67]
já tem data prevista pra vir?
sugestão: opção de filtrar mais jogadores além de 1 ou até filtro de liga > clube

**Comment by galodoido794** [comment]
Como eu trabalho então as melhorias tem que acontecer no meu horário "livre".

Logo, estou anotando as sugestões e quando voltar para melhorar o APP tentar fazer tudo de uma vez

**Comment by galodoido794** [comment]
https://github.com/galodoido794/AUTOBOT_FIFAX/issues/74
