### ISSUE TITLE
Parou de funcionar

### ISSUE THREAD

**Issue by Ptpain82** [galodoido794/AUTOBOT_FIFAX#68]
Boa tarde antes demais obrigado pela apk, é quase perfeita. Hoje de manhã deixou de funcionar, aparecendo a dizer que aconteceu um erro inesperado, já reinstalei já tentei de tudo mas não arranca o bot. Mais alguém com este problema? Um abraço

**Comment by galodoido794** [comment]
Esse do erro inesperado é algo que estou tentando investigar nesse outro [Tópico](https://github.com/galodoido794/AUTOBOT_FIFAX/issues/65)

**Comment by galodoido794** [comment]
https://github.com/galodoido794/AUTOBOT_FIFAX/issues/74
