### ISSUE TITLE
I wil onate 12$ to your patreon if you do this

### ISSUE THREAD

**Issue by Elmascapoy57** [galodoido794/AUTOBOT_FIFAX#69]
Hi i am a fan of your app and i would like if you would apply the bidding option and make everything instead of 3 seconds a little bit faster and also search in general not just one player if you do all of these i woul not only donate you 12$ but 50$ min.
Keep up the great job
Thanks

**Comment by galodoido794** [comment]
thanks for the contribution.
The app has a lot to improve regardless of the community's help. Of course, if the community helps itself with more resources, I would develop faster. However, this is not a problem to keep improving (it only takes longer)
------------------------------------------------pt-BR-------------------------
Obrigado pela contribuição.
O aplicativo tem muito que melhorar independentemente da ajuda da comunidade. Claro, que se a comunidade ajuda-se com mais recursos eu iria desenvolver mais rápido. Entretanto, isso não é um impecilho para continuar melhorando (só demora mais)

**Comment by galodoido794** [comment]
https://github.com/galodoido794/AUTOBOT_FIFAX/issues/74
