### ISSUE TITLE
still says logged into fifa any help ?

### ISSUE THREAD

**Issue by frostedfc** [galodoido794/AUTOBOT_FIFAX#7]

**Comment by galodoido794** [comment]
I'll check that later. I'm working :)

**Comment by juancuevas92** [comment]
Same issue for me, Error: Are you logged in to FIFA? Check ...

**Comment by Vorsah** [comment]
Wenn das Problem nach einem Neustart nochmal erscheint bedeutet dass das der Transfermarkt vorübergehend deaktiviert ist. 

Das betrifft jedoch nur die Web APP auf dem PC / Laptop, sprich du kannst auf deiner Konsole weiterhin Spieler kaufen. Diese Deaktivierung dauert jenach dem 4 - 24 Stunden.

**Comment by Vorsah** [comment]
Sry, it was German.
Here in English:

**Comment by Vorsah** [comment]
If the problem reappears after a reboot it means that the transfer market is temporarily disabled.

However, this only affects the Web APP on the PC / laptop, meaning you can continue to buy players on your console. This deactivation takes about 4 to 24 hours.

**Comment by juancuevas92** [comment]
Hi Vorsah, 
I still get the same error even tho I'm signed in using the program and after restart.


![image](https://user-images.githubusercontent.com/14003728/49178508-c4161380-f304-11e8-80b1-d182b681797f.png)

**Comment by kadiin** [comment]
Makes a manual transfer by the autobot that syncs there, it worked here for me.

**Comment by juancuevas92** [comment]
I keep getting same error, I listed some players using the software.

![image](https://user-images.githubusercontent.com/14003728/49237399-fc742b00-f3b2-11e8-95bb-7c9c18aa3b92.png)

But when I got back and search for Squad fitness I get the same error.

![image](https://user-images.githubusercontent.com/14003728/49237493-2d546000-f3b3-11e8-865c-80576ef8c25e.png)

**Comment by kadiin** [comment]
Try clear all caches of your browsers.

**Comment by juancuevas92** [comment]
Hi Kadiin, 

I did try that and still no luck, same error.

**Comment by galodoido794** [comment]
Is your date and time correct? If you are trying the following
clear the Chrome Cache
then click on the button on the right side "Problem with Login Fifa? Try this"
delete the (AUTOBOT) folder
Restart PC
puts the BOT in another folder and tries again.

lately I have a lot of work and the little time I have is not developing the BOT. 
So I've created a campaign: [Patreon](https://www.patreon.com/galodoido)

**Comment by juancuevas92** [comment]
Hi Galo, 
I tried step by step and it still didn't work.

Let me know if you want to have a remote session.

**Comment by galodoido794** [comment]
[En-Us]
As no one contributed anything (on the Patreon site) I am not giving support and will not have new features. While I'm working on other BOTs

[Pt-br]
Como ninguém contribuiu com nada (no site Patreon) não estou dando suporte e não vai vai ter novos recursos. Enquanto nisso estou trabalhando em outros BOTs

https://www.patreon.com/galodoido
