### ISSUE TITLE
how can i buy UCL Players with that autobuyer?

### ISSUE THREAD

**Issue by houston96** [galodoido794/AUTOBOT_FIFAX#70]
how do i buy a UCL player? in futhead copy 1st CODE or 2nd long cod? and in cheat put "GOLD" or "UCL"? for buying...help me, please..

**Comment by galodoido794** [comment]
I wanted to test it.
Do this with a cheaper player and it would help the community you post your
test (disseminating knowledge and helping other players)


Em qua., 11 de mar. de 2020 às 15:52, houston96 <notifications@github.com>
escreveu:

**Comment by houston96** [comment]
It doesn't work any of this.. please give me a solution..

**Comment by galodoido794** [comment]
Try to put quality *Gold* and the correct rating ...

Em sex., 13 de mar. de 2020 às 08:55, houston96 <notifications@github.com>
escreveu:

**Comment by houston96** [comment]
UCL players have the same rating as gold..

**Comment by galodoido794** [comment]
I'm not checking problem or suggestion right now because of the down warning:

Because of Covid19 I'm months without updating the FutAUTO, HOWEVER I'm coming back at the end of the month (August 2020) already thinking about FIFA 2021

**Comment by galodoido794** [comment]
https://github.com/galodoido794/AUTOBOT_FIFAX/issues/74
