### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by AaronJB1991** [galodoido794/AUTOBOT_FIFAX#71]
Anyone else getting the unexpected error message when trying to search for a card? Companion app works fine so it's not a temporary ban or anything. I have tried troubleshooting the app and my phone and nothing seems to work.

**Comment by pepepou** [comment]
Hace you solucionated the issue?

**Comment by pepepou** [comment]
Have*

**Comment by galodoido794** [comment]
I'm not checking problem or suggestion right now because of the down warning:

Because of Covid19 I'm months without updating the FutAUTO, HOWEVER I'm coming back at the end of the month (August 2020) already thinking about FIFA 2021

**Comment by galodoido794** [comment]
https://github.com/galodoido794/AUTOBOT_FIFAX/issues/74
