### ISSUE TITLE
App cannot buy the items

### ISSUE THREAD

**Issue by mguare** [galodoido794/AUTOBOT_FIFAX#72]
I'm receiving the following error when the app tray to buy the items
![Screenshot_20200506-194409](https://user-images.githubusercontent.com/7656315/81210463-34cd5f00-8fd2-11ea-8581-3b7a89727833.jpg)

What's happening?

**Comment by galodoido794** [comment]
I'm not checking problem or suggestion right now because of the down warning:

Because of Covid19 I'm months without updating the FutAUTO, HOWEVER I'm coming back at the end of the month (August 2020) already thinking about FIFA 2021

**Comment by galodoido794** [comment]
https://github.com/galodoido794/AUTOBOT_FIFAX/issues/74
