### ISSUE TITLE
Fifa 21

### ISSUE THREAD

**Issue by Samito022** [galodoido794/AUTOBOT_FIFAX#73]
Hi Galo, we all are waiting for update for fifa 21. Good work

**Comment by galodoido794** [comment]
I will prepare a new application trying to improve some features until the launch should be ready.

I will communicate through this website and youtube.

#FutAUTO21

**Comment by galodoido794** [comment]
https://github.com/galodoido794/AUTOBOT_FIFAX/issues/74
