### ISSUE TITLE
Mouse Cursor is not pointing at the right object on screen when selecting a player

### ISSUE THREAD

**Issue by juancuevas92** [galodoido794/AUTOBOT_FIFAX#8]
It might be because my laptop is using 3600x1800, what is the resolution of the computer you developed this with?

**Comment by galodoido794** [comment]
Actually I have not tested with this resolution until because my monitor is not 4K =(

I'll see what I do.

Entitled I created a campaign: [Patreon](https://www.patreon.com/galodoido)
