### ISSUE TITLE
Error when launch

### ISSUE THREAD

**Issue by Helda** [galodoido794/AUTOBOT_FIFAX#9]
![image](https://user-images.githubusercontent.com/3964346/49955378-f29a0e00-ff02-11e8-92e9-f168afe2afdd.png)
 Hi, when i launch your program i got error which you see on screen.

Translate error: Library mozglue.dll cannot load.

LOG version run normally. But in LOG version cannot see search panel.

OS version: Windows 10 Pro v.1809

Thanks for your reply.

**Comment by galodoido794** [comment]
1) Is your windows 64 or 32bit?
2) Do you have Firefox installed? Anything tries to install or upgrade to see if it resolves ...
